language: csharp
mono: none
dist: xenial
dotnet: 2.2
script:
  - dotnet restore
  - dotnet build -c Release
  - dotnet test
before_deploy:
  - dotnet publish FroniusSolarApi.Poller/FroniusSolarApi.Poller.csproj --output ../publish/ -c Release --runtime win-x64
  - zip FroniusSolarApi.PollerApp.zip publish/*
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: FroniusSolarApi.PollerApp.zip
  skip_cleanup: true
  draft: true
  on:
    tags: true
    branch: master