language: csharp
mono: none
dist: xenial
dotnet: 6.0.9
script:
  - dotnet restore
  - dotnet build -c Release --runtime win-x64
  - dotnet build -c Release --runtime linux-arm
  - dotnet test
before_deploy:
  - dotnet publish FroniusSolarApi.Poller/FroniusSolarApi.Poller.csproj --output ../publish/win-x64 -c Release --runtime win-x64
  - dotnet publish FroniusSolarApi.Poller/FroniusSolarApi.Poller.csproj --output ../publish/linux-arm -c Release --runtime linux-arm
  - zip FroniusSolarApi.PollerApp_win-x64.zip publish/win-x64/*
  - zip FroniusSolarApi.PollerApp_linux-arm.zip publish/linux-arm/*
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: 
    - "FroniusSolarApi.PollerApp_win-x64.zip"
    - "FroniusSolarApi.PollerApp_linux-arm.zip"
  skip_cleanup: true
  draft: true
  on:
    tags: true
    branch: master